# Generated by Django 3.0.8 on 2021-06-02 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='etudiant',
            name='admission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='adresse',
            field=models.CharField(default='rdc', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etudiant',
            name='mail',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etudiant',
            name='telephone',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('faculte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscription.Faculte')),
            ],
        ),
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bultin_6', models.FileField(upload_to='')),
                ('journal', models.FileField(upload_to='')),
                ('photo', models.FileField(upload_to='')),
                ('etudiant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inscription.Etudiant')),
            ],
        ),
        migrations.AddField(
            model_name='etudiant',
            name='filiere',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='inscription.Filiere'),
            preserve_default=False,
        ),
    ]
